apiVersion: 2019-12-01
location: France-Centre
name: countofmoney

properties:
  imageRegistryCredentials:
    - server: nodejscontainer.azurecr.io
      username: nodejscontainer
      password: gMCsAg/xHD3Win0lvHGdyBpZ451on7L3
  osType: Linux
  containers:
  - name: back
    properties:
      image: nodejscontainer.azurecr.io/countofmoneynode:v2
      environmentVariables:
      - name: 'NODE_ENV'
        value: 'prod'
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 8080

  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 8080
    dnsNameLabel:


tags: {exampleTag: tutorial}
type: Microsoft.ContainerInstance/containerGroups